alto=600
ancho=800
titulo="Pruebas Tauri"
redimensionable=true
decoraciones=true
datos=2
posicion=[1, 1]
[sprites]


[reproductor]
redimensionable=false
decoraciones=false

[paleta]
alto=400
ancho=400
